CREATE DATABASE Users;
GO
USE Users;

CREATE TABLE UserData(
ID INT IDENTITY PRIMARY KEY,
[NAME] NVARCHAR(95),
[SURNAME] NVARCHAR(95),
[EMAIL] NVARCHAR(95) UNIQUE,
[PHONE] INT
);

INSERT INTO UserData([NAME], [SURNAME], [EMAIL], [PHONE])
VALUES('IBAD', 'ISMAYILOV', 'IBAD@GMAIL.COM', 0000000000);

INSERT INTO UserData([NAME], [SURNAME], [EMAIL], [PHONE])
VALUES('IBAD2', 'ISMAYILOV2', 'IBAD2@GMAIL.COM', 0000000001)

INSERT INTO UserData([NAME], [SURNAME], [EMAIL], [PHONE])
VALUES('IBAD3', 'ISMAYILOV3', 'IBAD3@GMAIL.COM', 0000000002);

CREATE TABLE UserDetails (
    ID INT IDENTITY PRIMARY KEY,
    [ADDRESS] NVARCHAR(95),
    [GENDER] NVARCHAR(95),
    [EDUCATIONLEVEL] NVARCHAR(95),
    UserDataId INT FOREIGN KEY REFERENCES UserData(ID)
);

INSERT INTO UserDetails([ADDRESS], [GENDER], [EDUCATIONLEVEL], UserDataId)
VALUES('ADRESS', 'ADRESS', 'MASTER', 1);

UPDATE UserData SET [NAME] = 'SYSTEM', [SURNAME] = 'DEFAULT' WHERE [ID] = 1;

SELECT * FROM UserData;
SELECT * FROM UserDetails;